// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package json

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cmd int32

const (
	Cmd_Unknown    Cmd = 0
	Cmd_Auth       Cmd = 1
	Cmd_Push       Cmd = 2
	Cmd_Heartbeat  Cmd = 3
	Cmd_Close      Cmd = 4
	Cmd_ServerPush Cmd = 5
)

var Cmd_name = map[int32]string{
	0: "Unknown",
	1: "Auth",
	2: "Push",
	3: "Heartbeat",
	4: "Close",
	5: "ServerPush",
}

var Cmd_value = map[string]int32{
	"Unknown":    0,
	"Auth":       1,
	"Push":       2,
	"Heartbeat":  3,
	"Close":      4,
	"ServerPush": 5,
}

func (x Cmd) String() string {
	return proto.EnumName(Cmd_name, int32(x))
}

func (Cmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type Message struct {
	MagicNumber          uint32   `protobuf:"varint,1,opt,name=magicNumber,proto3" json:"magicNumber,omitempty"`
	Cmd                  Cmd      `protobuf:"varint,2,opt,name=cmd,proto3,enum=Cmd" json:"cmd,omitempty"`
	RequestId            uint32   `protobuf:"varint,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMagicNumber() uint32 {
	if m != nil {
		return m.MagicNumber
	}
	return 0
}

func (m *Message) GetCmd() Cmd {
	if m != nil {
		return m.Cmd
	}
	return Cmd_Unknown
}

func (m *Message) GetRequestId() uint32 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Message) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterEnum("Cmd", Cmd_name, Cmd_value)
	proto.RegisterType((*Message)(nil), "Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0xc6, 0x71, 0xdc, 0xb8, 0x94, 0x5c, 0x49, 0x65, 0xdd, 0x80, 0x3c, 0x30, 0x58, 0x4c, 0x11,
	0x43, 0x06, 0x18, 0x99, 0x20, 0x0b, 0x0c, 0xa0, 0x2a, 0x88, 0x85, 0xcd, 0xae, 0x8f, 0x16, 0x81,
	0x63, 0xf0, 0x0b, 0x88, 0x6f, 0x8f, 0x62, 0x06, 0xba, 0xfd, 0xf5, 0xd3, 0xdd, 0xf0, 0x40, 0xe3,
	0x28, 0x46, 0xbd, 0xa5, 0xee, 0x23, 0xf8, 0xe4, 0xcf, 0x32, 0x2c, 0xee, 0xff, 0x00, 0x15, 0x2c,
	0x9d, 0xde, 0xbe, 0x6e, 0x1e, 0xb2, 0x33, 0x14, 0x24, 0x53, 0xac, 0x6d, 0x86, 0x7d, 0xc2, 0x13,
	0xa8, 0x36, 0xce, 0xca, 0x99, 0x62, 0xed, 0xea, 0x82, 0x77, 0xbd, 0xb3, 0xc3, 0x04, 0x78, 0x0a,
	0x75, 0xa0, 0xcf, 0x4c, 0x31, 0xdd, 0x59, 0x59, 0x95, 0xbf, 0x7f, 0x40, 0x04, 0x6e, 0xbc, 0xfd,
	0x91, 0x5c, 0xb1, 0xb6, 0x1e, 0x4a, 0x9f, 0xaf, 0xa1, 0xea, 0x9d, 0xc5, 0x25, 0x2c, 0x9e, 0xc6,
	0xb7, 0xd1, 0x7f, 0x8f, 0xe2, 0x00, 0x8f, 0x80, 0x5f, 0xe7, 0xb4, 0x13, 0x6c, 0xaa, 0x75, 0x8e,
	0x3b, 0x31, 0xc3, 0x06, 0xea, 0x5b, 0xd2, 0x21, 0x19, 0xd2, 0x49, 0x54, 0x58, 0xc3, 0xbc, 0x7f,
	0xf7, 0x91, 0x04, 0xc7, 0x15, 0xc0, 0x23, 0x85, 0x2f, 0x0a, 0xe5, 0x72, 0x7e, 0x73, 0xfc, 0x0c,
	0xdd, 0x55, 0xd9, 0x64, 0xf2, 0x8b, 0x39, 0x2c, 0x75, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xe8,
	0xe3, 0x66, 0x02, 0xee, 0x00, 0x00, 0x00,
}
